# https://circleci.com/docs/2.1/language-javascript/
version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  setup:
    docker:
      - image: 'cimg/node:14.20.1'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - build/*
  lint_commit_message:
    docker:
      - image: 'cimg/node:14.20.1'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - attach_workspace:
          at: ./
      - run:
          name: Lint commit messages
          command: npx commitlint --from main --to HEAD --verbose
  test:
    docker:
      - image: 'cimg/node:14.20.1'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - attach_workspace:
          at: ./
      - run: npm test
      - run: npm run cov:send
      - run: npm run cov:check
  publish-docs:
    docker:
      - image: 'cimg/node:14.20.1'
    steps:
      - checkout
      - attach_workspace:
          at: node_modules
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Set git user email and name
          command: |
            git config user.email "willwin.wang@gmail.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - '66:28:0f:96:81:5c:9e:4c:2a:fe:39:76:d7:20:19:cd'
      - run: npm run doc:html
      - run: npm run doc:publish

workflows:
  build:
    jobs:
      - setup
      - lint_commit_message:
          requires:
            - setup
      - test:
          requires:
            - setup
      - publish-docs:
          filters:
            branches:
              only:
                - main
          requires:
            - lint_commit_message
            - test
